const data = [
    {
        id: '032',
        flatImage: 'interior1',
        name: 'Simanto villa',
        shortAddress: 'Khandar, Bogra',
        longAddress: 'Beside Passport Office, Gohail road, Bogra 5800, Bogra',
        price: '12,000',
        bedrooms: '4',
        bathrooms: '3',
        area: '1200',
        description: 'Suspendisse vitae turpis at nibh dictum dapibus. Donec vehicula condimentum felis, vel tincidunt arcu scelerisque quis. Etiam ac vestibulum leo. Aliquam augue tellus, vulputate et fringilla sit amet, vestibulum ut velit. Vestibulum purus massa, rhoncus id ultricies eget, mattis sit amet risus. Morbi a nibh blandit, viverra erat vitae, consequat mi. In elit ligula, egestas non diam id, pretium semper erat. Maecenas enim sem, condimentum sit amet pharetra at, tincidunt sit amet lacus. Morbi porttitor libero libero.',
        homeDetails: 'Suspendisse vitae turpis at nibh dictum dapibus. Donec vehicula condimentum felis, vel tincidunt arcu scelerisque quis. Etiam ac vestibulum leo. Aliquam augue tellus, vulputate et fringilla sit amet, vestibulum ut velit. Vestibulum purus massa, rhoncus id ultricies eget, mattis sit amet risus. Morbi a nibh blandit, viverra erat vitae, consequat mi. In elit ligula, egestas non diam id, pretium semper erat. Maecenas enim sem, condimentum sit amet pharetra at, tincidunt sit amet lacus. Morbi porttitor libero libero, varius malesuada metus malesuada sed. Etiam vehicula gravida massa. Nulla cursus finibus lacus. In condimentum leo at sapien venenatis tincidunt ac sit amet ante.',
        owner: 'Snigdha group',
        ownerJoiningDate: 'Joined OCT 2020',
        ownerDescription: 'Vitae turpis at nibh beddictum dapibus. Donec vehicula condimentum felis, vel tincidunt arcu scelerisque quis. Etiam ac vestibulum leo. Aliquam augue tellus, vulputate et fringilla sit amet, vestibulum ut velit.',
        ownerLang: ['Bangla', 'English'],
        ownerResponseTime: 'Within an hour',
        ownerContact: '+8801531709712',
        ownerEmail: 'snigdhaAbas',
    },
    {
        id: '058',
        flatImage: 'interior2',
        name: 'Simanto villa',
        shortAddress: 'Khandar, Bogra',
        longAddress: 'Beside Passport Office, Gohail road, Bogra 5800, Bogra',
        price: '8,000',
        bedrooms: '3',
        bathrooms: '3',
        area: '900',
        description: 'Suspendisse vitae turpis at nibh dictum dapibus. Donec vehicula condimentum felis, vel tincidunt arcu scelerisque quis. Etiam ac vestibulum leo. Aliquam augue tellus, vulputate et fringilla sit amet, vestibulum ut velit. Vestibulum purus massa, rhoncus id ultricies eget, mattis sit amet risus. Morbi a nibh blandit, viverra erat vitae, consequat mi. In elit ligula, egestas non diam id, pretium semper erat. Maecenas enim sem, condimentum sit amet pharetra at, tincidunt sit amet lacus. Morbi porttitor libero libero.',
        homeDetails: 'Suspendisse vitae turpis at nibh dictum dapibus. Donec vehicula condimentum felis, vel tincidunt arcu scelerisque quis. Etiam ac vestibulum leo. Aliquam augue tellus, vulputate et fringilla sit amet, vestibulum ut velit. Vestibulum purus massa, rhoncus id ultricies eget, mattis sit amet risus. Morbi a nibh blandit, viverra erat vitae, consequat mi. In elit ligula, egestas non diam id, pretium semper erat. Maecenas enim sem, condimentum sit amet pharetra at, tincidunt sit amet lacus. Morbi porttitor libero libero, varius malesuada metus malesuada sed. Etiam vehicula gravida massa. Nulla cursus finibus lacus. In condimentum leo at sapien venenatis tincidunt ac sit amet ante.',
        owner: 'Snigdha group',
        ownerJoiningDate: 'Joined OCT 2020',
        ownerDescription: 'Vitae turpis at nibh beddictum dapibus. Donec vehicula condimentum felis, vel tincidunt arcu scelerisque quis. Etiam ac vestibulum leo. Aliquam augue tellus, vulputate et fringilla sit amet, vestibulum ut velit.',
        ownerLang: ['Bangla', 'English'],
        ownerResponseTime: 'Within an hour',
        ownerContact: '+8801531709712',
        ownerEmail: 'snigdhaAbas',
    },
    {
        id: '066',
        flatImage: 'interior3',
        name: 'Simanto villa',
        shortAddress: 'Khandar, Bogra',
        longAddress: 'Beside Passport Office, Gohail road, Bogra 5800, Bogra',
        price: '12,000',
        bedrooms: '4',
        bathrooms: '3',
        area: '1200',
        description: 'Suspendisse vitae turpis at nibh dictum dapibus. Donec vehicula condimentum felis, vel tincidunt arcu scelerisque quis. Etiam ac vestibulum leo. Aliquam augue tellus, vulputate et fringilla sit amet, vestibulum ut velit. Vestibulum purus massa, rhoncus id ultricies eget, mattis sit amet risus. Morbi a nibh blandit, viverra erat vitae, consequat mi. In elit ligula, egestas non diam id, pretium semper erat. Maecenas enim sem, condimentum sit amet pharetra at, tincidunt sit amet lacus. Morbi porttitor libero libero.',
        homeDetails: 'Suspendisse vitae turpis at nibh dictum dapibus. Donec vehicula condimentum felis, vel tincidunt arcu scelerisque quis. Etiam ac vestibulum leo. Aliquam augue tellus, vulputate et fringilla sit amet, vestibulum ut velit. Vestibulum purus massa, rhoncus id ultricies eget, mattis sit amet risus. Morbi a nibh blandit, viverra erat vitae, consequat mi. In elit ligula, egestas non diam id, pretium semper erat. Maecenas enim sem, condimentum sit amet pharetra at, tincidunt sit amet lacus. Morbi porttitor libero libero, varius malesuada metus malesuada sed. Etiam vehicula gravida massa. Nulla cursus finibus lacus. In condimentum leo at sapien venenatis tincidunt ac sit amet ante.',
        owner: 'Snigdha group',
        ownerJoiningDate: 'Joined OCT 2020',
        ownerDescription: 'Vitae turpis at nibh beddictum dapibus. Donec vehicula condimentum felis, vel tincidunt arcu scelerisque quis. Etiam ac vestibulum leo. Aliquam augue tellus, vulputate et fringilla sit amet, vestibulum ut velit.',
        ownerLang: ['Bangla', 'English'],
        ownerResponseTime: 'Within an hour',
        ownerContact: '+8801531709712',
        ownerEmail: 'snigdhaAbas',
    },
    {
        id: '213',
        flatImage: 'interior4',
        name: 'Simanto villa',
        shortAddress: 'Khandar, Bogra',
        longAddress: 'Beside Passport Office, Gohail road, Bogra 5800, Bogra',
        price: '15,000',
        bedrooms: '5',
        bathrooms: '3',
        area: '1400',
        description: 'Suspendisse vitae turpis at nibh dictum dapibus. Donec vehicula condimentum felis, vel tincidunt arcu scelerisque quis. Etiam ac vestibulum leo. Aliquam augue tellus, vulputate et fringilla sit amet, vestibulum ut velit. Vestibulum purus massa, rhoncus id ultricies eget, mattis sit amet risus. Morbi a nibh blandit, viverra erat vitae, consequat mi. In elit ligula, egestas non diam id, pretium semper erat. Maecenas enim sem, condimentum sit amet pharetra at, tincidunt sit amet lacus. Morbi porttitor libero libero.',
        homeDetails: 'Suspendisse vitae turpis at nibh dictum dapibus. Donec vehicula condimentum felis, vel tincidunt arcu scelerisque quis. Etiam ac vestibulum leo. Aliquam augue tellus, vulputate et fringilla sit amet, vestibulum ut velit. Vestibulum purus massa, rhoncus id ultricies eget, mattis sit amet risus. Morbi a nibh blandit, viverra erat vitae, consequat mi. In elit ligula, egestas non diam id, pretium semper erat. Maecenas enim sem, condimentum sit amet pharetra at, tincidunt sit amet lacus. Morbi porttitor libero libero, varius malesuada metus malesuada sed. Etiam vehicula gravida massa. Nulla cursus finibus lacus. In condimentum leo at sapien venenatis tincidunt ac sit amet ante.',
        owner: 'Snigdha group',
        ownerJoiningDate: 'Joined OCT 2020',
        ownerDescription: 'Vitae turpis at nibh beddictum dapibus. Donec vehicula condimentum felis, vel tincidunt arcu scelerisque quis. Etiam ac vestibulum leo. Aliquam augue tellus, vulputate et fringilla sit amet, vestibulum ut velit.',
        ownerLang: ['Bangla', 'English'],
        ownerResponseTime: 'Within an hour',
        ownerContact: '+8801531709712',
        ownerEmail: 'snigdhaAbas',
    },
    {
        id: '332',
        flatImage: 'interior5',
        name: 'Simanto villa',
        shortAddress: 'Khandar, Bogra',
        longAddress: 'Beside Passport Office, Gohail road, Bogra 5800, Bogra',
        price: '6,000',
        bedrooms: '2',
        bathrooms: '2',
        area: '1000',
        description: 'Suspendisse vitae turpis at nibh dictum dapibus. Donec vehicula condimentum felis, vel tincidunt arcu scelerisque quis. Etiam ac vestibulum leo. Aliquam augue tellus, vulputate et fringilla sit amet, vestibulum ut velit. Vestibulum purus massa, rhoncus id ultricies eget, mattis sit amet risus. Morbi a nibh blandit, viverra erat vitae, consequat mi. In elit ligula, egestas non diam id, pretium semper erat. Maecenas enim sem, condimentum sit amet pharetra at, tincidunt sit amet lacus. Morbi porttitor libero libero.',
        homeDetails: 'Suspendisse vitae turpis at nibh dictum dapibus. Donec vehicula condimentum felis, vel tincidunt arcu scelerisque quis. Etiam ac vestibulum leo. Aliquam augue tellus, vulputate et fringilla sit amet, vestibulum ut velit. Vestibulum purus massa, rhoncus id ultricies eget, mattis sit amet risus. Morbi a nibh blandit, viverra erat vitae, consequat mi. In elit ligula, egestas non diam id, pretium semper erat. Maecenas enim sem, condimentum sit amet pharetra at, tincidunt sit amet lacus. Morbi porttitor libero libero, varius malesuada metus malesuada sed. Etiam vehicula gravida massa. Nulla cursus finibus lacus. In condimentum leo at sapien venenatis tincidunt ac sit amet ante.',
        owner: 'Snigdha group',
        ownerJoiningDate: 'Joined OCT 2020',
        ownerDescription: 'Vitae turpis at nibh beddictum dapibus. Donec vehicula condimentum felis, vel tincidunt arcu scelerisque quis. Etiam ac vestibulum leo. Aliquam augue tellus, vulputate et fringilla sit amet, vestibulum ut velit.',
        ownerLang: ['Bangla', 'English'],
        ownerResponseTime: 'Within an hour',
        ownerContact: '+8801531709712',
        ownerEmail: 'snigdhaAbas',
    },
    {
        id: '532',
        flatImage: 'interior6',
        name: 'Simanto villa',
        shortAddress: 'Khandar, Bogra',
        longAddress: 'Beside Passport Office, Gohail road, Bogra 5800, Bogra',
        price: '10,000',
        bedrooms: '3',
        bathrooms: '2',
        area: '1000',
        description: 'Suspendisse vitae turpis at nibh dictum dapibus. Donec vehicula condimentum felis, vel tincidunt arcu scelerisque quis. Etiam ac vestibulum leo. Aliquam augue tellus, vulputate et fringilla sit amet, vestibulum ut velit. Vestibulum purus massa, rhoncus id ultricies eget, mattis sit amet risus. Morbi a nibh blandit, viverra erat vitae, consequat mi. In elit ligula, egestas non diam id, pretium semper erat. Maecenas enim sem, condimentum sit amet pharetra at, tincidunt sit amet lacus. Morbi porttitor libero libero.',
        homeDetails: 'Suspendisse vitae turpis at nibh dictum dapibus. Donec vehicula condimentum felis, vel tincidunt arcu scelerisque quis. Etiam ac vestibulum leo. Aliquam augue tellus, vulputate et fringilla sit amet, vestibulum ut velit. Vestibulum purus massa, rhoncus id ultricies eget, mattis sit amet risus. Morbi a nibh blandit, viverra erat vitae, consequat mi. In elit ligula, egestas non diam id, pretium semper erat. Maecenas enim sem, condimentum sit amet pharetra at, tincidunt sit amet lacus. Morbi porttitor libero libero, varius malesuada metus malesuada sed. Etiam vehicula gravida massa. Nulla cursus finibus lacus. In condimentum leo at sapien venenatis tincidunt ac sit amet ante.',
        owner: 'Snigdha group',
        ownerJoiningDate: 'Joined OCT 2020',
        ownerDescription: 'Vitae turpis at nibh beddictum dapibus. Donec vehicula condimentum felis, vel tincidunt arcu scelerisque quis. Etiam ac vestibulum leo. Aliquam augue tellus, vulputate et fringilla sit amet, vestibulum ut velit.',
        ownerLang: ['Bangla', 'English'],
        ownerResponseTime: 'Within an hour',
        ownerContact: '+8801531709712',
        ownerEmail: 'snigdhaAbas',
    }
]

export default data;